name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - '.editorconfig'
      - '.spi.yml'
  pull_request:
    branches:
      - main

jobs:
  test_macos:
    name: Test macOS 15
    runs-on: macOS-15
    timeout-minutes: 10
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.1.app
    steps:
    - uses: actions/checkout@v4
    - name: test
      run: swift test

  test_linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install keys
        run: curl --silent --retry 3 --location --fail https://swift.org/keys/all-keys.asc | gpg --import -
      - name: Install swiftly
        run: curl -L https://swiftlang.github.io/swiftly/swiftly-install.sh | bash -s -- -y
      - name: Install the latest Swift toolchain
        run: swiftly install latest
      - name: Test
        run: swift test
