name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - '.editorconfig'
      - '.spi.yml'
  pull_request:
    branches:
      - main

jobs:
  test_macos:
    name: Test macOS 15
    runs-on: macOS-15
    timeout-minutes: 10
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.1.app
    steps:
    - uses: actions/checkout@v4
    - name: test
      run: swift test

  test_linux:
    name: Test Linux
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Swiftly
        uses: vapor/swiftly-action@v0.1.4
        with:
          toolchain: latest
      - name: Test
        run: swift test
